import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import {
  Navbar01,
  type Navbar01NavLink,
} from "@/components/ui/shadcn-io/navbar-01";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const navigationLinks: Navbar01NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/solutions", label: "Solutions" },
  { href: "/technology", label: "Technology" },
  { href: "/about", label: "About" },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Navbar01 navigationLinks={navigationLinks} signInHref="/admin" ctaHref="/sign-up" />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
