import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { type Navbar01NavLink } from "@/components/ui/shadcn-io/navbar-01";
import { Navbar05 } from "@/components/ui/shadcn-io/navbar-05";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const navigationLinks: Navbar01NavLink[] = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/digital-map", label: "Digital Map" },
];

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Navbar05 navigationLinks={navigationLinks} />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
